### ISSUE TITLE
Translator bug: Could not translate term into Viper expression for check!

### ISSUE THREAD

**Issue by jennalwise** [gradual-verification/silicon-gv#21]
The list_insert method below is erroring with this error: “Could not translate term into Viper expression for check!”. 
```
method list_insert(list: Ref, val: Int) returns ($result: Ref)
   requires ? && true
   ensures ? && true
 {
   var n: Ref
   var curr: Ref
   var tmp: Ref
   var prev: Ref
   n := null
   curr := null
   tmp := null
   prev := null
   if (list == null || val <= list.Node$val) {
     n := new(Node$val, Node$next)
     n.Node$val := val
     n.Node$next := list
     $result := n
   } else {
     curr := list
     while (curr.Node$next != null && curr.Node$next.Node$val < val)
       invariant ? && true 
     {
       prev := curr
       curr := prev.Node$next
       if (list == prev) {
         
       } else {
         appendLemmaLoopBody(list.Node$next, prev, curr, list.Node$val, prev.Node$val, prev.Node$val, curr.Node$val)
       }
     }
     tmp := new(Node$val, Node$next)
     tmp.Node$val := val
     tmp.Node$next := curr.Node$next
     curr.Node$next := tmp
     if (list == curr) {
       
     } else {
       appendLemmaAfterLoopBody(list.Node$next, curr, null, list.Node$val, curr.Node$val, -1)
     }
     $result := list
   }
 }
```

The specific term that it cannot translate is: `(! (or (== list@3@01 Null) (<= val@4@01 list@3@01.Node$val@18@01)))` and in particular `list@3@01.Node$val@18@01` is failing the translation. It is a branch condition that is being translated to create a run-time check for accessing `curr.Node$next != null` in the while loop condition, which happens in `chunkSupporter.lookupGreedy`. `list@3@01.Node$val@18@01` is not being found in the Heap, OH, or store, which is correct since there isn’t enough static information for the verifier to have access to this field in the Heap or OH at any point (even at the correct point where this path condition is being evaluated) and this field’s symbolic value cannot be found in the store. There are two problems here: 1) this branch condition is being translated with the wrong state, it just happens to work for the most part here; this is something already being addressed, 2) even if the right state is used, the heap, OH, and store will not contain anything to translate `list@3@01.Node$val@18@01` correctly. This should be fixed with the new change to translating branch conditions which removes the need for translation entirely. However, will this same problem arise during run-time check translation? If so, my proposed solution would be to apply the regex solution we applied to nested field accesses to singular field accesses as well in the case that we cannot use the heaps to find the right translated value.

**Comment by hgouni** [comment]
This has been fixed by 3239dded
