### ISSUE TITLE
Short Circuiting Eval is Producing Run-time Checks in Produce

### ISSUE THREAD

**Issue by jennalwise** [gradual-verification/silicon-gv#27]
Short circuiting And/Or evaluation is being used in `produce` when evaluating conditions in if conditionals (found in this https://github.com/gradual-verification/gvc0/blob/master/src/test/resources/bugs/state_merge.c0 example; conditions in if conditionals are the only places where short circuiting seems to be used in `produce` instead of regular `eval`). Short circuiting eval is creating run-time checks for framing. No run-time checks for framing should be created during a `produce`. The only run-time checks that should be generated during a `produce` are ones for branching when one of the branches fails to statically verify. However, run-time checks should be produced by short circuiting eval outside of `produce`, such as in `consume`.

**Comment by jennalwise** [comment]
@hemantgouni Hold off on fixing this for now, because we might need to produce some run-time checks for framing conditions when producing the body of a predicate at an unfold. I need to look into this more.

**Comment by jennalwise** [comment]
@hemantgouni Go ahead and implement a fix for this bug, thanks!

**Comment by hgouni** [comment]
Alright! I'll work on this shortly
