### ISSUE TITLE
Static profiler reporting incorrect numbers for full static solution in list.c0 and for predicate_vars.c0

### ISSUE THREAD

**Issue by jennalwise** [gradual-verification/silicon-gv#28]
The static profiler is reporting 632 total conjuncts and 630 eliminated conjuncts for the statically specified version of `list.c0`. In our meeting, Hemant and I narrowed down one of the discrepancies to possibly not counting the framing of the if statement’s condition in `list_insert`. Further, debugging by Hemant has led to the `v.decider.checkSmoke()` case in `ChunkSupporter` occurring. This case occurs when the symbolic state is unsatisfiable, aka. for dead code. Profiling information is not being collected in this case. It is possible that this case is reachable for real programs, but why is it occurring for a correct fully specified program? Answering this question will likely lead to a correct solution to this issue.

**Comment by jennalwise** [comment]
Not sure if this is related but I noticed the following:

For https://github.com/gradual-verification/gvc0/blob/master/src/test/resources/bugs/predicate_vars.c0 the verifier is reporting 39 total conjuncts to 36 statically verified conjuncts. However, there are 9 correctly produced run-time checks by the verifier, so this number seems off. I also observed the verifier counting two conjuncts as statically verified when consuming `wrappedAcc(b)` and `wrappedAcc(a)` at the end of `sumNodes`. However, shouldn’t it just be one? Also, in both of these cases the verifier optimistically assumes it has access to these predicates and produces run-time checks for them, so the verifier should not count them as statically verified.

**Comment by hgouni** [comment]
The issue with predicate_vars.c0 has been fixed in eaf035a99c0e70f4a28af88b575b75f3d6ac83b6. I still have to figure out why checkSmoke returns true occasionally (if we increment conjuncts in that case, the static profiling turns out fine for the list.c0 case, too).
