### ISSUE TITLE
 Backend not printing run-time checks

### ISSUE THREAD

**Issue by jennalwise** [gradual-verification/silicon-gv#31]
https://github.com/gradual-verification/gvc0/blob/master/src/test/resources/bugs/condition_version.c0 when run through the frontend and full pipeline produces a .c0 file with the correct run-time check injected. The full pipeline also reports the correct run-time check is being given to the frontend by the backend. Also, the backend reports the correct number of statically verified conjuncts. However, when looking at the debugging output of the file when run in the backend only, the printed run-time checks map is empty. This doesn’t happen for files where more than 1 run-time check is produced or at least I haven’t witnessed this issue for c0 programs that produce 0 or more than 1 run-time check.

**Comment by hgouni** [comment]
I've resolved this in commit 745a4c29798ba827fb29991aef847ca2ee607518.
